name: Action test
on:
  push
jobs:
  test:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: depend action
        uses: ./
        with: 
          nasm: true
          cache: true
          doxygen: true
