name: Build check
on:
  pull_request:
    branches:
      - dev
      - master
  push:
    branches:
      - dev
      - master
permissions:
  contents: read
jobs:
  build:
    name: Try to build installer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      
      - name: Configure CMake
        run: |
          mkdir -p ${{ github.workspace }}/build
          cmake ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release
        
      - name: Build the project
        run: |
          cd ${{ github.workspace }}/build
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: ${{ github.workspace }}/build/depend
