name: Versioning
on:
  pull_request:
    branches:
      - dev
      - master
  push:
    branches:
      - dev
      - master
permissions:
  contents: write
jobs:
  create_version:
    name: Create version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run Git Version
        id: version
        uses: codacy/git-version@2.8.0

      - name: Create tag
        run: git tag ${{ steps.version.outputs.version }}

      - name: Upload tag
        run: git push origin ${{ steps.version.outputs.version }}
